

### Render OAuth Github
GET https://task-manager-hc4o.onrender.com/auth/github

### Render Logout
GET https://task-manager-hc4o.onrender.com/auth/logout

### Localhost OAuth Github
GET http://localhost:3030/auth/github


###Post in localhost:3030
POST http://localhost:3030/users
Content-Type: application/json

{
   "username": "Slugger",
   "fullName": " perkins",
   "email": "baseballfan@gmail.com",
   "password": "thisPassword",
   "tasksAssigned": []
}

### GET all users in localhost:3030
GET http://localhost:3030/users

### GET a user by ID
GET http://localhost:3030/users/6525ff262a1e70b7324f68b4

### PUT Change one user info by ID
PUT http://localhost:3030/users/65307c41fe857d4c058939be
Content-Type: application/json

{
  "username": "Slugger",
  "fullName": "perkins",
  "email": "baseball@gmail.com",
  "password": "thisPassword",
   "tasksAssigned": []
}

### POST in Render
POST https://task-manager-hc4o.onrender.com/users
Content-Type: application/json

{
  "username": "Fuzzy Bunny Slinpm startppers",
   "fullName": "Jan Gilbert",
   "email": "fuzzyBunny@geemail.com",
   "password": "thisPassword",
   "tasksAssigned": []
}

### GET all users on Render
GET https://task-manager-hc4o.onrender.com/users